sample_object:

  dataset: /path_to_object/dataset

  # for inference
  weights: [{path: /path_to_weights/best.pt,
              type: SWIN-UNET # YOLO, SETR-PUP
              }]
  # for SETR-PUP:
  # weights: [{
  #         path: {
  #           backbone: path_to_mae_encoder/mae_encoder_for_segmentation.pth,
  #           head: path_to_mae_head/best_model.pth
  #           },
  #         type: SETR-PUP
  #         }]
  
  labels: ['sample_object_1', 'sample_object_2']
  confidence: 0.1
  result_folder_name: results

  device: cpu # or cuda
  model: yolo11n.pt # train model, setr-pup, vit-mae, swin-mae, swin-unet, pup-head 
  model_config: {
    epochs: 50,
    patience: 20,
    
    # for autoencoders
    visualize_steps: true,
    visualize_frequency: 25,

    # for heads train
    head_epochs: 300,
    head_visualize_steps: true,
    head_visualize_frequency: 25,
    encoder_path: path_to_encoder/setrpup_encoder.pth
  }

  # tasks 
  train: false 
  detect: true
  annotate: true
